import "./globals.css";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";
import { AppProps } from "next/app";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  pageProps,
}: PropsWithChildren<AppProps>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers pageProps={pageProps}>{children}</Providers>
      </body>
    </html>
  );
}
